name: Deploy next.js docker portfolio

on:
  push:
    branches: [ main ]

jobs:
  build:
    # Type of runner
    runs-on: ubuntu-latest

    steps:
    - name: Deploy using ssh
      uses: appleboy/ssh-action@master
      env:
        SERVER_PATH: ${{ vars.SERVER_PATH }}
      with:
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        port: ${{ secrets.SERVER_PORT }}
        envs: SERVER_PATH
        script: |
            cd "$SERVER_PATH" || exit  

            # Mise à jour du dépôt
            git pull origin main
              
            # Destruction des anciens conteneurs et suppression de l'ancienne image
            docker-compose down --rmi all || true
              
            # Construction de la nouvelle image et lancement du conteneur
            docker-compose up -d --build