name: Deploy next.js docker portfolio

on:
  push:
    branches: [ main ]

jobs:
  build:
    # Type of runner
    runs-on: ubuntu-latest

    steps:
    - name: Deploy using ssh
      uses: appleboy/ssh-action@master
      env:
        SERVER_PATH: ${{ vars.SERVER_PATH }}
      with:
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        port: ${{ secrets.SERVER_PORT }}
        envs: SERVER_PATH
        script: |
            echo "SERVER_PATH: $SERVER_PATH"
            cd $SERVER_PATH || exit  

            # Mise à jour du dépot
            git pull origin main
              
            # Destruction des anciens conteneurs
            docker stop portfolio || true
            docker rm portfolio || true
              
            # Suppression de l'ancienne image
            docker rmi portfolio-image || true
              
            # Construction de la nouvelle image Docker
            docker build -t portfolio-image .
              
            # Lancement du nouveau conteneur
            docker run -d --name portfolio -p 3000:3000 portfolio-image